### ISSUE TITLE
Support for UWP applications ? 

### ISSUE THREAD

**Issue by pchnl** [MrC0rrupted/WinLaunch#42]
I must say that WinLaunch is an incredible nice menu system. Very well done !
I was wondering if it is possible to attach Universal Windows Platform applications such as the apps from the Microsoft Store ? 
For example Affinity Photo v2. 
These applications cause me a lot of problem anyway with their weird shortcuts. 
They live in the shell:AppsFolder  but I am not able to drag and drop any of them onto WinLaunch. 
Any ideas / advise ?

**Comment by MrC0rrupted** [comment]
Hey, thanks.
You can drag them to the Desktop from the shell:AppsFolder first, then you can drag them into WinLaunch from there.

After they are in WinLaunch, you can delete the desktop version again, and it should keep working, it's the only workaround I've found so far, since there doesn't seem to be an API for shell:AppsFolder for non UWP apps.

**Comment by pchnl** [comment]
That is awesome. It works as you describe. Thank you. 
At first, the icons look _smallish_ on my 4K monitor. When I sign-out of windows and sign back in, they are resized and much better (closing WinLaunch is not enough; I need to sign out of windows). 
I think WinLaunch work so well that I am going to use it as my default menu system. Besides regular programs I have a single page with all the projects I am working on. On the page, I have "groups", one for each project. Within the group are shortcuts to folders, shares, files, applications, etc. that I use in the project. This works better than all the other "file launchers" / "project organizers" I have found on windows.
